server:
  port: 8776
foo: bar_8776-aaa2
spring:
  rabbitmq:  # eureka-client通过rabbitmq接收通知触发刷新配置
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:  # 暴露bus-refresh节点（默认只暴露health和info）
        include: '*'
  security:
    enabled: false  # 需关闭 spring security，否则禁止访问 bus-refresh
